shopsys_shop:
    resource: "@ShopsysShopBundle/Resources/config/routing.yml"
    prefix: /

shopsys_framework:
    resource: "@ShopsysFrameworkBundle/Resources/config/routing.yml"
  
elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"

admin_flag_delete:
    path: /admin/product/flag/delete/{id}?routeCsrfToken={routeCsrfToken}
    defaults: { _controller: ShopsysShopBundle:Front\Error:notFound }
    requirements:
        id: \d+

admin_flag_list:
    path: /admin/product/flag/list/
    defaults: { _controller: ShopsysShopBundle:Front\Error:notFound }

admin_customer_edit:
    path: /admin/customer/edit/{billingAddressId}
    defaults: { _controller: ShopsysShopBundle:Admin\Customer:edit }
    requirements:
        billingAddressId: \d+

admin_customer_delete:
    path: /admin/customer/delete/{billingAddressId}
    defaults: { _controller: ShopsysShopBundle:Admin\Customer:delete }
    requirements:
        billingAddressId: \d+
