imports:
  - { resource: forms.yml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Shopsys\ShopBundle\Controller\:
    resource: '../../Controller/'
    public: true
    tags: ['controller.service_arguments']

  Shopsys\ShopBundle\Model\:
    resource: '../../Model/*/*{Facade,Factory}.php'

  League\Flysystem\MountManager:
    arguments:
      -
        local: '@local_filesystem'
        main: '@main_filesystem'

  Shopsys\ShopBundle\Form\Front\Order\DomainAwareOrderFlowFactory: ~

  Shopsys\FrameworkBundle\Model\Order\OrderFlowFactoryInterface: '@Shopsys\ShopBundle\Form\Front\Order\DomainAwareOrderFlowFactory'

  Shopsys\FrameworkBundle\Model\Article\ArticleFactoryInterface: '@Shopsys\ShopBundle\Model\Article\ArticleFactory'

  Shopsys\FrameworkBundle\Model\Article\ArticleDataFactoryInterface: '@Shopsys\ShopBundle\Model\Article\ArticleDataFactory'

  Shopsys\ShopBundle\Model\Category\CurrentCategoryResolver: ~

  Shopsys\FrameworkBundle\Model\Product\ProductFactoryInterface: '@Shopsys\ShopBundle\Model\Product\ProductFactory'

  Shopsys\FrameworkBundle\Model\Product\ProductDataFactoryInterface: '@Shopsys\ShopBundle\Model\Product\ProductDataFactory'

  League\Flysystem\FilesystemInterface: '@main_filesystem'
