framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler:
        enabled: true
        collect: true
        only_exceptions: false
        only_master_requests: true
