assetic:
    debug: "%kernel.debug%"
    use_controller: false
    bundles: [FMElfinderBundle]
    filters:
        cssrewrite: ~
    assets:
        js_form_validation:
            # Missing file with compiled JS is a known bug of the package - https://github.com/formapro/JsFormValidatorBundle/issues/109
            inputs:
                - "%shopsys.vendor_dir%/fp/jsformvalidator-bundle/Fp/JsFormValidatorBundle/Resources/public/js/FpJsFormValidator.js"
                - "%shopsys.vendor_dir%/fp/jsformvalidator-bundle/Fp/JsFormValidatorBundle/Resources/public/js/constraints/*"
                - "%shopsys.vendor_dir%/fp/jsformvalidator-bundle/Fp/JsFormValidatorBundle/Resources/public/js/transformers/*"
                - "%shopsys.vendor_dir%/fp/jsformvalidator-bundle/Fp/JsFormValidatorBundle/Resources/public/js/jquery.fpjsformvalidator.js"
            # Output is located in vendor (instead of /web/bundles/fpjsformvalidator/js/fp_js_validator.js)
            # because "phing assets" command cleans the /web/bundles directory and would remove the compiled script
            output: "%shopsys.js_form_validator_output_vendor_dir%/fp/jsformvalidator-bundle/Fp/JsFormValidatorBundle/Resources/public/js/fp_js_validator.js"
